library(plyr)
f_widths <- matrix(as.integer(16), 561, 1)
features <- read.table (file = "UCI HAR Dataset/features.txt", header = FALSE, sep = " ", col.names = c("f_num", "f_name"), as.is = TRUE)
x_train<- read.fwf(file = "UCI HAR Dataset/train/X_train.txt", widths = f_widths[,1], header = FALSE, col.names = features$f_name, buffersize = 100)
y_train<- read.table(file = "UCI HAR Dataset/train/y_train.txt", header = FALSE, col.names = "act_num")
s_train<- read.table(file = "UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
train<- cbind(x_train, y_train, s_train)
x_test<- read.fwf(file = "UCI HAR Dataset/test/X_test.txt", widths = f_widths[,1], header = FALSE, col.names = features$f_name, buffersize = 100)
y_test<- read.table(file = "UCI HAR Dataset/test/y_test.txt", header = FALSE, col.names = "act_num")
s_test<- read.table(file = "UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
test<- cbind(x_test, y_test, s_test)
all_data<-rbind(train, test)
filtered_data <- all_data[,grepl("mean()|std()|act_num|subject", x = names(all_data)) & !grepl("meanFreq", x = names(all_data))]
act_labels <- read.table (file = "UCI HAR Dataset/activity_labels.txt", header = FALSE, sep = " ", col.names = c("act_num", "act_label"), as.is = TRUE)
filtered_labeled_data<- merge(x = filtered_data, y = act_labels, by = "act_num")
act_sub_means<- ddply(filtered_labeled_data, c('act_label', 'subject'), function(x) c(colMeans(x[,2:67])))
write.table(x = act_sub_means, file = "act_sub_means.txt", row.name=FALSE)